### ISSUE TITLE
todos

### ISSUE THREAD

**Issue by joreg** [vvvv/VL.Devices.ZED#3]
- [x] update to 4.1 (mention in overview help)
- [x] flip auto doesn't seem to work
- [x] SVO realtime mode: what happens if off? should it be on by default?
- [x] extract reboot node from main ZED process, consider ID correctly
- [x] on ZED node: rename "SVO Path" -> "Filename" -> add pin summary: Supply a .svo for playback 
- [x] why are image-resolution, fov, fps, isopen not on update?
- [x] hide input type and device id? or move them further right?
- [x] svo writing help opens with error
- [x] rename: ZEDRecorder -> SVORecorder, Path input -> Filename
- [x] rename: SVOPlaybackControls -> SVOPlayer
- [x] SVORecorder: have one bool input "Record" instead of two bangs start/stop
- [x] SVOPlayer rename inputs: Frame -> Seek Frame, Jump To Frame -> Seek
- [x] ZED node: create, update, dispose, tovector, toquaternion should not show up in nodebrowser

**Comment by joreg** [comment]
- [x] making a recording to filename "foo.svo" results in a file on disk named "foo.svo2"
- [x] svo playback doesn't seem to work
- [x] would it make sense to have the svo file not specified on the main ZED node but on the SVOPlayer node?
- [x] show warning on ZED/ZEDPlayer nodes while downloading model

**Comment by rmtttt** [comment]
regarding *.svo2:
https://www.stereolabs.com/developers/release#recording-using-svo2-16d9e6349727
"The older format can still be recorded by setting the environment variable ZED_SDK_SVO_VERSION to 1."

**Comment by joreg** [comment]
- extract all player functionality from main ZED node into extra ZEDPlayer node (combined with stuff currently in SVOPlayer)
- ZED and ZEDPlayer nodes returns IDevice
- ZEDRecorder takes in IDevice

**Comment by joreg** [comment]
- [x] Simply placing 2 ZED nodes crashes vvvv
- [x] When not being online while needing to download a model, the ZED node crashes with a null exception
- [x] Add visualizer to skeleton help patch
